### ISSUE TITLE
Nuke 15 : error interpreting this pugin

### ISSUE THREAD

**Issue by DerickYau** [vinavfx/ComfyUI-for-Nuke#12]
Nuke versions: Nuke 15.0 v4, Nuke 15.1v2
ComfyUI version: v0.2.1 Lora fixes
Error Message:

NukeStudio 15.1v2, 64 bit, built Jul 19 2024.
Copyright (c) 2024 The Foundry Visionmongers Ltd.  All Rights Reserved.

Traceback (most recent call last):
  File "C:/Users/About/.nuke/menu.py", line 8, in <module>
    import ComfyUI as comfyui
  File "C:\Program Files\Nuke15.1v2\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/About/.nuke\ComfyUI\__init__.py", line 8, in <module>
    from .src import *
  File "C:\Program Files\Nuke15.1v2\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/About/.nuke\ComfyUI\src\__init__.py", line 1, in <module>
    from . import (
  File "C:\Program Files\Nuke15.1v2\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/About/.nuke\ComfyUI\src\common.py", line 8, in <module>
    from ..env import COMFYUI_DIR, NUKE_USER
  File "C:\Program Files\Nuke15.1v2\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users/About/.nuke\ComfyUI\env.py", line 1, in <module>
    from .nuke_util.nuke_util import get_nuke_path
  File "C:\Program Files\Nuke15.1v2\pythonextensions\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'ComfyUI.nuke_util.nuke_util'

![000](https://github.com/user-attachments/assets/0f2010e3-4e4b-46e0-8930-030f468351f7)
![111](https://github.com/user-attachments/assets/2056c9c2-67e8-4bf2-864f-38f3c91d83e1)
![01](https://github.com/user-attachments/assets/e51419b6-e4e0-4e8f-893f-1e7cb9b6d05c)
![02](https://github.com/user-attachments/assets/0aa7b5a5-6c6d-4837-9421-0a54a1478289)

Thank you so much.

**Comment by vinavfx** [comment]
can't have that name, the folder in .nuke has to be called "nuke_comfyui" not "ComfyUI"

**Comment by DerickYau** [comment]
> 不能有这个名字，.nuke 中的文件夹必须叫“nuke_comfyui”而不是“ComfyUI”，如果不是这样，那么你没有递归克隆：git clone recursive ...或手动复制以下 2 个库：https://github.com/vinavfx/nuke_util 和 https://github.com/vinavfx/python_util

Problem solved.
Prior to this, when doing git clone --recursive, there had been problems with the network, so I just downloaded the zip and copied it into the .nuke folder.
This time i used     git clone --recursive...  , and the problem was solved.
Thanks again.
